//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTful_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASKLIST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TASKLIST()
        {
            this.TASK = new HashSet<TASK>();
        }
    
        public int TASKLISTID { get; set; }
        public string TASKLISTNAME { get; set; }
        public string TASKLISTDESCRIPTION { get; set; }
        public int FK_USER_TASKLIST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK> TASK { get; set; }
        public virtual USER_ACCOUNT USER_ACCOUNT { get; set; }
    }
}
