//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTful_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK
    {
        public int TASKID { get; set; }
        public string TASKNAME { get; set; }
        public string TASKDESCRIPTION { get; set; }
        public bool TASKSTATUS { get; set; }
        public int FK_USER_TASK { get; set; }
        public int FK_TASKLIST_TASK { get; set; }
    
        public virtual TASKLIST TASKLIST { get; set; }
        public virtual USER_ACCOUNT USER_ACCOUNT { get; set; }
    }
}
