//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTful_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ACCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER_ACCOUNT()
        {
            this.TASK = new HashSet<TASK>();
            this.TASKLIST = new HashSet<TASKLIST>();
        }
    
        public int USERACCOUNTID { get; set; }
        public string USERNAME { get; set; }
        public string USERPASSWORD { get; set; }
        public string USERIMAGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK> TASK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASKLIST> TASKLIST { get; set; }
    }
}
